### ISSUE TITLE
[Amélioration] Tableau images

### ISSUE THREAD

**Issue by jerrywham** [Fred89/Uforum#1]
Actuellement, les appels d'images sont gérés par la fonction img qui recherche un index dans le tableau $img_names afin d'afficher l'image correspondante générée préalablement (lors de la construction du forum) après un base64_decode du contenu du tableau $images_array.

Ne serait-il pas plus simple de n'avoir qu'un seul tableau $img dont les index serait le nom des images et les valeurs les code en base 64 ? 

Ainsi, avec la fonction img(), on saurait qu'elle est l'image que l'on appelle (et on n'aurait pas ainsi à se souvenir de l'ordre des index), et on pourrait directement l'afficher sans la générer, en faisant :
&lt;img src="data:image/png;base64,'.$img['avatar'].'"/&gt;

**Comment by Fred89** [comment]
Pas bête en effet, mais l'utilisateur ne pourras pas changer / remplacer les images facilement s'il veut personnaliser.
